In [4]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array to DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)


# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Create 100 dates from 2023-01-01 to 2023-04-09
dates = pd.date_range(start='2023-01-01', end='2023-04-09')

# Create the DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(
        ['East', 'West', 'North', 'South'],
        size=num_rows
    ),
    'Product': np.random.choice(
        ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        size=num_rows
    ),
    'Sales': np.random.randint(100, 1001, size=num_rows),
    'Quantity': np.random.randint(1, 11, size=num_rows),
})

# Introduce NaN values
sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan


# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Select rows where Region is East AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

# 3.4 Get Sales value for the first Monitor entry using .loc and .iloc
monitor_indices = df_sales.index[df_sales['Product'] == 'Monitor']

if len(monitor_indices) > 0:
    first_monitor_index = monitor_indices[0]
    val3_4 = df_sales.loc[first_monitor_index, 'Sales']
else:
    val3_4 = np.nan


# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isna().sum()

# 4.2 Fill missing Sales values with the mean Sales
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(
    df4_2_filled['Sales'].mean()
)

# 4.3 Drop rows containing any missing values
df4_3_dropped = df_sales.dropna()


# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2 Sort by Date ascending, then Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[
    ['Sales', 'Quantity']
].sum()

# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()


# Optional: Display results
print("\n--- Task 1 Results ---")
print(s1_1)
print(np_array1_2)
print(df1_3)

print("\n--- Task 2 Results ---")
print(df_sales.head())

print("\n--- Task 3 Results ---")
print(df3_1.head())
print(df3_2.head())
print(df3_3.head())
print("First Monitor Sales:", val3_4)

print("\n--- Task 4 Results ---")
print("Missing values:")
print(missing_counts4_1)
print("\nFilled DataFrame:")
print(df4_2_filled.head())
print("\nDropped DataFrame:")
print(df4_3_dropped.head())

print("\n--- Task 5 Results ---")
print(df5_2_sorted.head())
print("\nGrouped by Region:")
print(df5_3_grouped_region)
print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

--- Task 2: Synthetic Data Generation for Practice ---

--- Task 3: Indexing and Slicing in DataFrames ---

--- Task 4: Data Cleaning (Handling Missing Values) ---

--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

--- Task 1 Results ---
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[ 92  35  52  13]
 [ 80   3 100  24]
 [ 84  53  78  51]]
    A   B    C   D
0  92  35   52  13
1  80   3  100  24
2  84  53   78  51

--- Task 2 Results ---
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01  North   Monitor  513.0       4.0         2052.0
1 2023-01-02   East   Monitor    NaN      10.0            NaN
2 2023-01-03   West     Mouse  916.0       1.0          916.0
3 2023-01-04   West    Laptop  115.0       4.0          460.0
4 2023-01-05   West